# Hexo Configuration
# Site
title: 硬件Base
subtitle: '记录，思考，应用'
description: '硬件Base：记录，思考，应用。一个关注技术、硬件、生活与长期思考的中文个人博客。'
keywords: 硬件Base, 哲普, 硬件, 技术博客, 中文博客, 个人网站
author: 哲普
language: zh-CN
timezone: Asia/Shanghai

# URL
# 当前正式网址。绑定自定义域名后，将这里替换为新的地址。
url: https://hardwarebase.top
permalink: posts/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: '  '
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page
index_generator:
  path: ''
  per_page: 8
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata
meta_generator: true

# Date / Time
date_format: YYYY-MM-DD
time_format: HH:mm
updated_option: mtime

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude
include:
exclude:
ignore:

# Extensions
theme: butterfly

# Feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content: true
  content_limit: 140
  content_limit_delim: ' '

# Sitemap
sitemap:
  path: sitemap.xml
  rel: false
  tags: true
  categories: true

# Local search database
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Local server
server:
  compress: true
  header: true

# Deployment
deploy:
  type: ''